package de.mosbach.lan.smarthome.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2016-03-24T11:01:53.057+01:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://services.smarthome.lan.mosbach.de/", name = "airConditionerService")
@XmlSeeAlso({ObjectFactory.class})
public interface AirConditionerService {

    @WebMethod
    @RequestWrapper(localName = "addAirConditioner", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.AddAirConditioner")
    @ResponseWrapper(localName = "addAirConditionerResponse", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.AddAirConditionerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public long addAirConditioner(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "turnOffAirConditioner", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.TurnOffAirConditioner")
    @ResponseWrapper(localName = "turnOffAirConditionerResponse", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.TurnOffAirConditionerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean turnOffAirConditioner(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "turnOnAirConditioner", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.TurnOnAirConditioner")
    @ResponseWrapper(localName = "turnOnAirConditionerResponse", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.TurnOnAirConditionerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean turnOnAirConditioner(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getAllAirConditioners", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.GetAllAirConditioners")
    @ResponseWrapper(localName = "getAllAirConditionersResponse", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.GetAllAirConditionersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<de.mosbach.lan.smarthome.services.AirConditioner> getAllAirConditioners();

    @WebMethod
    @RequestWrapper(localName = "removeAirConditioner", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.RemoveAirConditioner")
    @ResponseWrapper(localName = "removeAirConditionerResponse", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.RemoveAirConditionerResponse")
    public void removeAirConditioner(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
