
package de.mosbach.lan.smarthome.services;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2016-03-24T11:01:53.053+01:00
 * Generated source version: 2.7.0
 * 
 */
public final class AirConditionerService_AirConditionerService_Client {

    private static final QName SERVICE_NAME = new QName("http://services.smarthome.lan.mosbach.de/", "airConditionerService");

    private AirConditionerService_AirConditionerService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AirConditionerService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AirConditionerService_Service ss = new AirConditionerService_Service(wsdlURL, SERVICE_NAME);
        AirConditionerService port = ss.getAirConditionerService();  
        
        {
        System.out.println("Invoking addAirConditioner...");
        java.lang.String _addAirConditioner_arg0 = "";
        long _addAirConditioner__return = port.addAirConditioner(_addAirConditioner_arg0);
        System.out.println("addAirConditioner.result=" + _addAirConditioner__return);


        }
        {
        System.out.println("Invoking turnOffAirConditioner...");
        java.lang.String _turnOffAirConditioner_arg0 = "";
        boolean _turnOffAirConditioner__return = port.turnOffAirConditioner(_turnOffAirConditioner_arg0);
        System.out.println("turnOffAirConditioner.result=" + _turnOffAirConditioner__return);


        }
        {
        System.out.println("Invoking turnOnAirConditioner...");
        java.lang.String _turnOnAirConditioner_arg0 = "";
        boolean _turnOnAirConditioner__return = port.turnOnAirConditioner(_turnOnAirConditioner_arg0);
        System.out.println("turnOnAirConditioner.result=" + _turnOnAirConditioner__return);


        }
        {
        System.out.println("Invoking getAllAirConditioners...");
        java.util.List<de.mosbach.lan.smarthome.services.AirConditioner> _getAllAirConditioners__return = port.getAllAirConditioners();
        System.out.println("getAllAirConditioners.result=" + _getAllAirConditioners__return);


        }
        {
        System.out.println("Invoking removeAirConditioner...");
        java.lang.String _removeAirConditioner_arg0 = "";
        port.removeAirConditioner(_removeAirConditioner_arg0);


        }

        System.exit(0);
    }

}
