package de.mosbach.lan.smarthome.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2016-03-24T11:00:48.215+01:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://services.smarthome.lan.mosbach.de/", name = "HeaterService")
@XmlSeeAlso({ObjectFactory.class})
public interface HeaterService {

    @WebMethod
    @RequestWrapper(localName = "removeHeater", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.RemoveHeater")
    @ResponseWrapper(localName = "removeHeaterResponse", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.RemoveHeaterResponse")
    public void removeHeater(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "addHeater", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.AddHeater")
    @ResponseWrapper(localName = "addHeaterResponse", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.AddHeaterResponse")
    @WebResult(name = "return", targetNamespace = "")
    public long addHeater(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getAllHeaters", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.GetAllHeaters")
    @ResponseWrapper(localName = "getAllHeatersResponse", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.GetAllHeatersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<de.mosbach.lan.smarthome.services.Heater> getAllHeaters();

    @WebMethod
    @RequestWrapper(localName = "getHeaterByRoomName", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.GetHeaterByRoomName")
    @ResponseWrapper(localName = "getHeaterByRoomNameResponse", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.GetHeaterByRoomNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public de.mosbach.lan.smarthome.services.Heater getHeaterByRoomName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "turnOnHeater", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.TurnOnHeater")
    @ResponseWrapper(localName = "turnOnHeaterResponse", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.TurnOnHeaterResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean turnOnHeater(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "turnOffHeater", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.TurnOffHeater")
    @ResponseWrapper(localName = "turnOffHeaterResponse", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.TurnOffHeaterResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean turnOffHeater(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
