
package de.mosbach.lan.smarthome.services;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2016-03-24T11:00:48.209+01:00
 * Generated source version: 2.7.0
 * 
 */
public final class HeaterService_HeaterService_Client {

    private static final QName SERVICE_NAME = new QName("http://services.smarthome.lan.mosbach.de/", "heaterService");

    private HeaterService_HeaterService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HeaterService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HeaterService_Service ss = new HeaterService_Service(wsdlURL, SERVICE_NAME);
        HeaterService port = ss.getHeaterService();  
        
        {
        System.out.println("Invoking removeHeater...");
        java.lang.String _removeHeater_arg0 = "";
        port.removeHeater(_removeHeater_arg0);


        }
        {
        System.out.println("Invoking addHeater...");
        java.lang.String _addHeater_arg0 = "";
        long _addHeater__return = port.addHeater(_addHeater_arg0);
        System.out.println("addHeater.result=" + _addHeater__return);


        }
        {
        System.out.println("Invoking getAllHeaters...");
        java.util.List<de.mosbach.lan.smarthome.services.Heater> _getAllHeaters__return = port.getAllHeaters();
        System.out.println("getAllHeaters.result=" + _getAllHeaters__return);


        }
        {
        System.out.println("Invoking getHeaterByRoomName...");
        java.lang.String _getHeaterByRoomName_arg0 = "";
        de.mosbach.lan.smarthome.services.Heater _getHeaterByRoomName__return = port.getHeaterByRoomName(_getHeaterByRoomName_arg0);
        System.out.println("getHeaterByRoomName.result=" + _getHeaterByRoomName__return);


        }
        {
        System.out.println("Invoking turnOnHeater...");
        java.lang.String _turnOnHeater_arg0 = "";
        boolean _turnOnHeater__return = port.turnOnHeater(_turnOnHeater_arg0);
        System.out.println("turnOnHeater.result=" + _turnOnHeater__return);


        }
        {
        System.out.println("Invoking turnOffHeater...");
        java.lang.String _turnOffHeater_arg0 = "";
        boolean _turnOffHeater__return = port.turnOffHeater(_turnOffHeater_arg0);
        System.out.println("turnOffHeater.result=" + _turnOffHeater__return);


        }

        System.exit(0);
    }

}
