package de.mosbach.lan.smarthome.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2016-03-24T11:00:25.346+01:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://services.smarthome.lan.mosbach.de/", name = "windowService")
@XmlSeeAlso({ObjectFactory.class})
public interface WindowService {

    @WebMethod
    @RequestWrapper(localName = "getWindowById", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.GetWindowById")
    @ResponseWrapper(localName = "getWindowByIdResponse", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.GetWindowByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public de.mosbach.lan.smarthome.services.Window getWindowById(
        @WebParam(name = "windowId", targetNamespace = "")
        long windowId
    );

    @WebMethod
    @RequestWrapper(localName = "openWindow", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.OpenWindow")
    @ResponseWrapper(localName = "openWindowResponse", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.OpenWindowResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean openWindow(
        @WebParam(name = "roomName", targetNamespace = "")
        java.lang.String roomName
    );

    @WebMethod
    @RequestWrapper(localName = "addWindow", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.AddWindow")
    @ResponseWrapper(localName = "addWindowResponse", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.AddWindowResponse")
    @WebResult(name = "return", targetNamespace = "")
    public long addWindow(
        @WebParam(name = "roomName", targetNamespace = "")
        java.lang.String roomName
    );

    @WebMethod
    @RequestWrapper(localName = "getAllWindows", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.GetAllWindows")
    @ResponseWrapper(localName = "getAllWindowsResponse", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.GetAllWindowsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<de.mosbach.lan.smarthome.services.Window> getAllWindows();

    @WebMethod
    @RequestWrapper(localName = "removeWindow", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.RemoveWindow")
    @ResponseWrapper(localName = "removeWindowResponse", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.RemoveWindowResponse")
    public void removeWindow(
        @WebParam(name = "windowId", targetNamespace = "")
        long windowId
    );

    @WebMethod
    @RequestWrapper(localName = "closeWindow", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.CloseWindow")
    @ResponseWrapper(localName = "closeWindowResponse", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.CloseWindowResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean closeWindow(
        @WebParam(name = "roomName", targetNamespace = "")
        java.lang.String roomName
    );

    @WebMethod
    @RequestWrapper(localName = "getWindowsByRoomName", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.GetWindowsByRoomName")
    @ResponseWrapper(localName = "getWindowsByRoomNameResponse", targetNamespace = "http://services.smarthome.lan.mosbach.de/", className = "de.mosbach.lan.smarthome.services.GetWindowsByRoomNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<de.mosbach.lan.smarthome.services.Window> getWindowsByRoomName(
        @WebParam(name = "roomName", targetNamespace = "")
        java.lang.String roomName
    );
}
